// MobileTerminalAppDelegate.m
// MobileTerminal

#import "MobileTerminalAppDelegate.h"
#import "MobileTerminalViewController.h"

#import "Preferences/Settings.h"
#import "Preferences/MenuSettings.h"

// Automatically generated by build rules
#import "svnversion.h"
#define IPAD ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad)

@implementation MobileTerminalAppDelegate

@synthesize window;
@synthesize navigationController;
@synthesize terminalViewController;
@synthesize preferencesViewController;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [[UISwitch appearance] setOnTintColor:[[[UIColor alloc] initWithRed:0.11 green:0.47 blue:0.94 alpha:1] autorelease]];
    [[UISwitch appearance] setTintColor:[[[UIColor alloc] initWithRed:0.11 green:0.47 blue:0.94 alpha:1] autorelease]];
    NSUserDefaults *ud = [NSUserDefaults standardUserDefaults];
    NSString *result = [ud objectForKey:@"AlreadyLaunched"];
    
    if(![result isEqual:@"Yes"]){
        NSLog(@"WelcomeTerminal!!");
        [ud setObject:@"Basic" forKey:@"colorMap"];
        [ud setObject:@"Yes" forKey:@"AlreadyLaunched"];
        [ud setBool:false forKey:@"BlackOrWhite"];
        [ud setBool:false forKey:@"KeyboardTypeURL"];
        [ud setObject:@"Courier" forKey:@"font-Name"];
        [ud setObject:IPAD?[NSNumber numberWithFloat:19.0]:[NSNumber numberWithFloat:11.0] forKey:@"font-Size"];
        [ud synchronize];
    }
    
    if (![ud objectForKey:@"Term_Background"]) {
        [ud setObject:[NSKeyedArchiver archivedDataWithRootObject:[UIColor colorWithRed:0 green:0 blue:0 alpha:1]] forKey:@"Term_Background"];
        [ud setObject:[NSKeyedArchiver archivedDataWithRootObject:[UIColor colorWithRed:0.2 green:0.8 blue:0 alpha:1]] forKey:@"Term_Text"];
        [ud setObject:[NSKeyedArchiver archivedDataWithRootObject:[UIColor colorWithRed:0.6 green:0 blue:0 alpha:1]] forKey:@"Term_BoldText"];
        [ud setObject:[NSKeyedArchiver archivedDataWithRootObject:[UIColor colorWithRed:0.6 green:0 blue:0 alpha:1]] forKey:@"Term_Cursor"];
    }

    Settings* settings = Settings.sharedInstance;
    settings.svnVersion = 8.2;
    self.window = [[[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]] autorelease]; // Fixed 4 inch problem
    [[UIApplication sharedApplication] setStatusBarHidden:YES];
    
    NSMutableArray* viewControllers = [[[NSMutableArray alloc] init] autorelease];
    [viewControllers addObject:terminalViewController];
    [navigationController setViewControllers:viewControllers animated:NO];

    self.window.rootViewController = navigationController;
    float version = [[UIDevice currentDevice].systemVersion floatValue];
    if (version >= 8.0) {
        navigationController.navigationBar.layer.shadowOffset = CGSizeMake(1, 0);
        navigationController.navigationBar.layer.shadowColor = [[UIColor blackColor] CGColor];
        navigationController.navigationBar.layer.shadowRadius = 3;
        navigationController.navigationBar.layer.shadowOpacity = .25;
    }

    [window makeKeyAndVisible];
    inPreferences = FALSE;
    
    /* Navigation color */
    [UINavigationBar appearance].TintColor = [UIColor blackColor];
    [UINavigationBar appearance].barTintColor = [UIColor whiteColor];
    
    /* http://stackoverflow.com/questions/19226965/how-to-hide-ios7-uinavigationbar-1px-bottom-line */
    UINavigationBar *navigationBar = self.navigationController.navigationBar;
    UIImageView *navBarHairlineImageView = [self findHairlineImageViewUnder:navigationBar];
    navBarHairlineImageView.hidden = YES;
    
    if ([application respondsToSelector:@selector(registerUserNotificationSettings:)]) {
        UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeAlert|UIUserNotificationTypeSound categories:nil];
        [application registerUserNotificationSettings:settings];
    }
    
    [[UIApplication sharedApplication] setMinimumBackgroundFetchInterval:UIApplicationBackgroundFetchIntervalNever];
    return YES;
}

- (void)application:(UIApplication *)application performFetchWithCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
    completionHandler(UIBackgroundFetchResultNoData);
}

/* http://stackoverflow.com/questions/19226965/how-to-hide-ios7-uinavigationbar-1px-bottom-line */
- (UIImageView *)findHairlineImageViewUnder:(UIView *)view {
    if ([view isKindOfClass:UIImageView.class] && view.bounds.size.height <= 1.0) {
        return (UIImageView *)view;
    }
    for (UIView *subview in view.subviews) {
        UIImageView *imageView = [self findHairlineImageViewUnder:subview];
        if (imageView) return imageView;
    }
    return nil;
}

// static const NSTimeInterval kAnimationDuration = 1.00f;

- (void)preferencesButtonPressed
{
  inPreferences = TRUE;

  [navigationController setNavigationBarHidden:NO];

  [navigationController pushViewController:preferencesViewController animated:YES];
}

- (void)rootViewDidAppear
{
    
  inPreferences = TRUE;
    
}

@end
